### ISSUE TITLE
tfirst=True Bug

### ISSUE THREAD

**Issue by bulmust** [WarrenWeckesser/odeintw#4]
Hello,
I think I found a small bug in the code:

Here is my code:
```
import scipy.integrate as integ
import numpy as np
global frequaaa,frequaaa2
frequaaa=50
frequaaa2=50
def func(t,y):
    tmp=np.array([[[np.cos(frequaaa*t),np.sin(frequaaa*t)],[t,t**2]],\
        [[2*np.cos(frequaaa2*t),3*np.sin(frequaaa2*t)],[2*t,3*t**2]]],dtype=complex)
    return tmp.flatten()
y0=np.array([[[0,1],[0,0]],[[0,1],[0,0]]],dtype=complex).flatten()
t_min=0
t_max=10
N_max=250
t_min2=np.linspace(t_min,t_max,N_max)

import odeintw as aaa
solutionODEINT,info=aaa.odeintw(func,y0,t_min2,tfirst=True, atol=1e-10,\
                            rtol=1e-12,full_output=True)
```

The code gives an error:

```
Traceback (most recent call last):
  File "test_3dArrayComplex.py", line 24, in <module>
    rtol=1e-12,full_output=True)
  File "/usr/local/lib/python3.5/dist-packages/odeintw/_odeintw.py", line 226, in odeintw
    result = odeint(func2, y0.view(np.float64), t, Dfun=jacfunc2, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/scipy/integrate/odepack.py", line 244, in odeint
    int(bool(tfirst)))
  File "/usr/local/lib/python3.5/dist-packages/odeintw/_odeintw.py", line 194, in realfunc
    z = y.view(np.complex128)
AttributeError: 'float' object has no attribute 'view'
```

But if I delete `tfirst=True` and switch the function variables `func(t,y)` to `func(y,t)` than the code runs correctly.

**Comment by WarrenWeckesser** [comment]
Thanks for the bug report.  That's not a "small" bug, it's a regular-sized bug. 😃 

I added the `tfirst` argument to SciPy's `odeint` in version 1.1 of SciPy, but I never got around to handling it in `odeintw`.  It is on the "to do" list now.

**Comment by WarrenWeckesser** [comment]
@bulmust, I fixed the problem in the master branch on github.  I'll try to make a new release within a few days.

**Comment by TejasAvinashShetty** [comment]
Faced the same bug @WarrenWeckesser
