### ISSUE TITLE
using ravel to flatten a matrix will return a matrix with 1 row

### ISSUE THREAD

**Issue by bancsorin10** [WarrenWeckesser/odeintw#8]
this escalates since odeint does not recognize a 1 row matrix as a one dimension array.
```
Traceback (most recent call last):
  File "/home/sorin/HDD/faculta/faculta/anu4/sem1/rsc-roboticsystemscontrol/lab/lab8/test.py", line 74, in <module>
    x = odeintw(model,x0,tspan,args=(u[i],))
  File "/home/sorin/HDD/faculta/faculta/anu4/sem1/rsc-roboticsystemscontrol/lab/python/lib/python3.9/site-packages/odeintw/_odeintw.py", line 228, in odeintw
    result = odeint(func2, y0.view(np.float64), t, Dfun=jacfunc2, **kwargs)
  File "/home/sorin/HDD/faculta/faculta/anu4/sem1/rsc-roboticsystemscontrol/lab/python/lib/python3.9/site-packages/scipy/integrate/odepack.py", line 246, in odeint
    output = _odepack.odeint(func, y0, t, args, Dfun, col_deriv, ml, mu,
ValueError: Initial condition y0 must be one-dimensional.
```

I would try to replace `y0.ravel` with `np.asarray(y0).reshape(-1)` (this solved the problem for me)

**Comment by WarrenWeckesser** [comment]
Thanks, @bancsorin10.  I finally got around to fixing this.
